//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimMaliyeti.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class depo
    {
        public int urunID { get; set; }
        public int birimFiyat { get; set; }
        public int receteID { get; set; }
        public int birimMiktar { get; set; }
        public int derece { get; set; }
    }
}
